import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="cards">
          <div className="one">one</div>
          <div className="two">two</div>
          <div className="three">three</div>
          <div className="four">four</div>
          <div className="five">five</div>
          <div className="six">six</div>
          <div className="seven">seven</div>
          <div className="eight">eight</div>
          <div className="nine another">nine</div>
          <div className="ten another">ten</div>
          <div className="elleven another">elleven</div>
          <div className="twelve another">twelve</div>
        </div>
      </main>
    </div>
  );
}
